name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build-deps
      run: apt-get install libfuse-dev
    - name: make
      run: make
